import { Badge } from '../types/badge';

export const PREDEFINED_BADGES: Omit<Badge, 'current_supply' | 'created_at'>[] = [
  // Streak Badges
  {
    id: 'streak_7',
    name: '7-Day Streak',
    description: 'Maintained a 7-day streak',
    icon_emoji: '🔥',
    image_url: null,
    badge_category: 'streak',
    multiplier: 1.1,
    rarity: 'common',
    requirements: { streak_days: 7 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'streak_14',
    name: '14-Day Streak',
    description: 'Maintained a 14-day streak',
    icon_emoji: '🔥',
    image_url: null,
    badge_category: 'streak',
    multiplier: 1.2,
    rarity: 'rare',
    requirements: { streak_days: 14 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'streak_30',
    name: '30-Day Streak',
    description: 'Maintained a 30-day streak',
    icon_emoji: '🔥',
    image_url: null,
    badge_category: 'streak',
    multiplier: 1.5,
    rarity: 'epic',
    requirements: { streak_days: 30 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'streak_60',
    name: '60-Day Streak',
    description: 'Maintained a 60-day streak',
    icon_emoji: '🔥',
    image_url: null,
    badge_category: 'streak',
    multiplier: 2.0,
    rarity: 'epic',
    requirements: { streak_days: 60 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'streak_90',
    name: '90-Day Streak',
    description: 'Maintained a 90-day streak',
    icon_emoji: '🔥',
    image_url: null,
    badge_category: 'streak',
    multiplier: 2.5,
    rarity: 'legendary',
    requirements: { streak_days: 90 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'streak_180',
    name: '180-Day Streak',
    description: 'Maintained a 180-day streak',
    icon_emoji: '🔥',
    image_url: null,
    badge_category: 'streak',
    multiplier: 3.0,
    rarity: 'legendary',
    requirements: { streak_days: 180 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'streak_365',
    name: '365-Day Streak',
    description: 'Maintained a full year streak',
    icon_emoji: '🔥',
    image_url: null,
    badge_category: 'streak',
    multiplier: 5.0,
    rarity: 'legendary',
    requirements: { streak_days: 365 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },

  // Achievement Badges
  {
    id: 'founding_member',
    name: 'Founding Member',
    description: 'First 10,000 users',
    icon_emoji: '👑',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 2.0,
    rarity: 'legendary',
    requirements: { user_number_max: 10000 },
    max_supply: 10000,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'early_adopter',
    name: 'Early Adopter',
    description: 'Joined in Month 1',
    icon_emoji: '🎁',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 2.5,
    rarity: 'legendary',
    requirements: { joined_within_days: 30 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'launch_week',
    name: 'Launch Week Hero',
    description: 'Joined in first week',
    icon_emoji: '🎉',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 3.0,
    rarity: 'legendary',
    requirements: { joined_within_days: 7 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'millionaire',
    name: 'Millionaire',
    description: 'Earned 1,000,000 points',
    icon_emoji: '💰',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 1.5,
    rarity: 'epic',
    requirements: { total_points: 1000000 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'multi_millionaire',
    name: 'Multi-Millionaire',
    description: 'Earned 10,000,000 points',
    icon_emoji: '💰',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 2.0,
    rarity: 'legendary',
    requirements: { total_points: 10000000 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'top_100',
    name: 'Elite Farmer',
    description: 'Reached top 100 on leaderboard',
    icon_emoji: '🏆',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 2.0,
    rarity: 'legendary',
    requirements: { leaderboard_rank: 100 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'top_10',
    name: 'Top 10 Legend',
    description: 'Reached top 10 on leaderboard',
    icon_emoji: '🏆',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 3.0,
    rarity: 'legendary',
    requirements: { leaderboard_rank: 10 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'influencer',
    name: 'Influencer',
    description: 'Referred 100+ users',
    icon_emoji: '🌟',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 1.75,
    rarity: 'epic',
    requirements: { referrals: 100 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'mega_influencer',
    name: 'Mega Influencer',
    description: 'Referred 1000+ users',
    icon_emoji: '🌟',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 2.5,
    rarity: 'legendary',
    requirements: { referrals: 1000 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'box_master',
    name: 'Box Master',
    description: 'Opened 1000 boxes',
    icon_emoji: '📦',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 1.3,
    rarity: 'rare',
    requirements: { boxes_opened: 1000 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'lightning',
    name: 'Lightning Fast',
    description: 'Opened 10 boxes in 1 hour',
    icon_emoji: '⚡',
    image_url: null,
    badge_category: 'achievement',
    multiplier: 1.2,
    rarity: 'rare',
    requirements: { boxes_per_hour: 10 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },

  // Wallet Badges
  {
    id: 'wallet_connected',
    name: 'Wallet Connected',
    description: 'Connected TON wallet',
    icon_emoji: '👛',
    image_url: null,
    badge_category: 'wallet',
    multiplier: 1.1,
    rarity: 'common',
    requirements: { wallet_connected: true },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'whale',
    name: 'Whale',
    description: 'Hold 10+ TON in wallet',
    icon_emoji: '🐋',
    image_url: null,
    badge_category: 'wallet',
    multiplier: 2.0,
    rarity: 'legendary',
    requirements: { ton_balance: 10 },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
  {
    id: 'nft_holder',
    name: 'NFT Collector',
    description: 'Own any TON NFT',
    icon_emoji: '💎',
    image_url: null,
    badge_category: 'wallet',
    multiplier: 1.5,
    rarity: 'epic',
    requirements: { has_nfts: true },
    max_supply: null,
    is_active: true,
    available_from: null,
    available_until: null,
    can_convert_to_nft: true,
  },
];
