import { BadgeCategory, BadgeRarity } from '../types/badge';

export const BADGE_DEFINITIONS = [
  // STREAK BADGES
  {
    name: 'First Steps',
    description: 'Complete your first daily check-in',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.COMMON,
    requirement_type: 'streak',
    requirement_value: 1,
    points_reward: 100,
    multiplier_bonus: 0,
    icon_url: '/badges/first-steps.png',
    color: '#10B981',
  },
  {
    name: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.COMMON,
    requirement_type: 'streak',
    requirement_value: 7,
    points_reward: 500,
    multiplier_bonus: 0.1,
    icon_url: '/badges/week-warrior.png',
    color: '#3B82F6',
  },
  {
    name: 'Month Master',
    description: 'Maintain a 30-day streak',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.RARE,
    requirement_type: 'streak',
    requirement_value: 30,
    points_reward: 3000,
    multiplier_bonus: 0.25,
    icon_url: '/badges/month-master.png',
    color: '#8B5CF6',
  },
  {
    name: 'Century Legend',
    description: 'Maintain a 100-day streak',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.EPIC,
    requirement_type: 'streak',
    requirement_value: 100,
    points_reward: 15000,
    multiplier_bonus: 0.5,
    icon_url: '/badges/century-legend.png',
    color: '#F59E0B',
  },
  {
    name: 'Eternal Flame',
    description: 'Maintain a 365-day streak',
    category: BadgeCategory.STREAK,
    rarity: BadgeRarity.LEGENDARY,
    requirement_type: 'streak',
    requirement_value: 365,
    points_reward: 100000,
    multiplier_bonus: 1.0,
    icon_url: '/badges/eternal-flame.png',
    color: '#EF4444',
  },

  // POINTS BADGES
  {
    name: 'First Thousand',
    description: 'Earn 1,000 total points',
    category: BadgeCategory.POINTS,
    rarity: BadgeRarity.COMMON,
    requirement_type: 'total_points',
    requirement_value: 1000,
    points_reward: 100,
    multiplier_bonus: 0.05,
    icon_url: '/badges/first-thousand.png',
    color: '#10B981',
  },
  {
    name: 'Point Collector',
    description: 'Earn 10,000 total points',
    category: BadgeCategory.POINTS,
    rarity: BadgeRarity.RARE,
    requirement_type: 'total_points',
    requirement_value: 10000,
    points_reward: 1000,
    multiplier_bonus: 0.15,
    icon_url: '/badges/point-collector.png',
    color: '#3B82F6',
  },
  {
    name: 'Point Millionaire',
    description: 'Earn 1,000,000 total points',
    category: BadgeCategory.POINTS,
    rarity: BadgeRarity.LEGENDARY,
    requirement_type: 'total_points',
    requirement_value: 1000000,
    points_reward: 50000,
    multiplier_bonus: 0.5,
    icon_url: '/badges/point-millionaire.png',
    color: '#F59E0B',
  },

  // BOX BADGES
  {
    name: 'Box Opener',
    description: 'Open your first box',
    category: BadgeCategory.BOXES,
    rarity: BadgeRarity.COMMON,
    requirement_type: 'boxes_opened',
    requirement_value: 1,
    points_reward: 50,
    multiplier_bonus: 0,
    icon_url: '/badges/box-opener.png',
    color: '#10B981',
  },
  {
    name: 'Box Hunter',
    description: 'Open 100 boxes',
    category: BadgeCategory.BOXES,
    rarity: BadgeRarity.RARE,
    requirement_type: 'boxes_opened',
    requirement_value: 100,
    points_reward: 1000,
    multiplier_bonus: 0.1,
    icon_url: '/badges/box-hunter.png',
    color: '#8B5CF6',
  },

  // REFERRAL BADGES
  {
    name: 'First Friend',
    description: 'Refer your first friend',
    category: BadgeCategory.REFERRALS,
    rarity: BadgeRarity.COMMON,
    requirement_type: 'referrals',
    requirement_value: 1,
    points_reward: 200,
    multiplier_bonus: 0.05,
    icon_url: '/badges/first-friend.png',
    color: '#10B981',
  },
  {
    name: 'Social Butterfly',
    description: 'Refer 10 friends',
    category: BadgeCategory.REFERRALS,
    rarity: BadgeRarity.RARE,
    requirement_type: 'referrals',
    requirement_value: 10,
    points_reward: 2000,
    multiplier_bonus: 0.2,
    icon_url: '/badges/social-butterfly.png',
    color: '#EC4899',
  },

  // SPECIAL BADGES
  {
    name: 'Founding Member',
    description: 'One of the first 10,000 users',
    category: BadgeCategory.SPECIAL,
    rarity: BadgeRarity.LEGENDARY,
    requirement_type: 'user_number',
    requirement_value: 10000,
    points_reward: 10000,
    multiplier_bonus: 2.0,
    icon_url: '/badges/founding-member.png',
    color: '#F59E0B',
  },
  {
    name: 'Launch Week Hero',
    description: 'Joined during launch week',
    category: BadgeCategory.SPECIAL,
    rarity: BadgeRarity.EPIC,
    requirement_type: 'launch_week',
    requirement_value: 1,
    points_reward: 5000,
    multiplier_bonus: 1.5,
    icon_url: '/badges/launch-week.png',
    color: '#8B5CF6',
  },
] as const;
